server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/sharding_db?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: top.zsmile.db.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
